### ISSUE TITLE
Cannot run uikit-site

### ISSUE THREAD

**Issue by lupuxyz** [uikit/uikit-site#41] opened 2017-03-11 12:27 UTC
After translated the uikit docs into Chinese,...
I cannot run it with "npm run setup"
ERROR information:
![errors](https://cloud.githubusercontent.com/assets/8073971/23823226/f76e8ad2-0698-11e7-89e2-8f3a6475ba3d.png)

**Comment by Serexx** [comment] 2017-03-11 18:47
Similar problem after cloning the repo onto a W10 machine - can't read above screen shot but for me setup initially ran and then failed with ". is not a recognized command or batch file" - I'll see if i can revisit evaluating the framework once this is fixed.

**Comment by panda1111** [comment] 2017-03-28 10:59
I have the same issue. Also running W10.

**Comment by yahuaska** [comment] 2017-03-28 11:36
You should install bower first.

**Comment by lya0** [comment] 2017-03-30 07:25
U need install bower,less,rollup-plugin-node-resolve,fs,path with global。
And edit package.json the script "compile-less" to this:
"compile-less": "mkdir css &&lessc less/theme.less > css/theme.css --relative-urls --rootpath=../less/ -x"

**Comment by Intiligent** [comment] 2017-04-10 16:25
I have some problem with setup project. I followed recommendations from @lya0 and insall global bower, less, rollup-plugin-node-resolve, fs, path and edit "compile-less" to this:
"compile-less": "mkdir css && lessc less/theme.less > css/theme.css --relative-urls --rootpath=../less/ -x"
but i have error:
![uikit-npm-error](https://cloud.githubusercontent.com/assets/2857625/24871678/1e1c5988-1e23-11e7-8dbe-9b712c17305d.png)
npm-debur.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'bugs',
1 verbose cli   'uikit-site' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 silly mapToRegistry name uikit-site
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'uikit-site',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   name: 'uikit-site',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/uikit-site
9 verbose request uri https://registry.npmjs.org/uikit-site/latest
10 verbose request no auth needed
11 info attempt registry request try #1 at 19:20:20
12 verbose request id 1cd4deecc1ef34c8
13 http request GET https://registry.npmjs.org/uikit-site/latest
14 http 404 https://registry.npmjs.org/uikit-site/latest
15 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '51',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Mon, 10 Apr 2017 16:20:18 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-hhn1545-HHN',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1491841218.484044,VS0,VE329' }
16 silly get cb [ 404,
16 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 silly get     'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '51',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Mon, 10 Apr 2017 16:20:18 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-hhn1545-HHN',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1491841218.484044,VS0,VE329' } ]
17 verbose stack Error: 404 Not Found: uikit-site
17 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:250:14)
17 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
17 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:199:22)
17 verbose stack     at emitTwo (events.js:87:13)
17 verbose stack     at Request.emit (events.js:172:7)
17 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1036:10)
17 verbose stack     at emitOne (events.js:82:20)
17 verbose stack     at Request.emit (events.js:169:7)
17 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:963:12)
18 verbose statusCode 404
19 verbose pkgid uikit-site
20 verbose cwd E:\OpenServer\domains\uikit-site
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "uikit-site"
23 error node v4.4.4
24 error npm  v2.15.1
25 error code E404
26 error 404 Not Found: uikit-site
26 error 404
26 error 404 'uikit-site' is not in the npm registry.
26 error 404 You should bug the author to publish it (or use the name yourself!)
26 error 404
26 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

```

In what my wrong?

**Comment by lya0** [comment] 2017-04-15 07:10
@Intiligent 
```
8 silly mapToRegistry uri https://registry.npmjs.org/uikit-site
9 verbose request uri https://registry.npmjs.org/uikit-site/latest
10 verbose request no auth needed
11 info attempt registry request try #1 at 19:20:20
12 verbose request id 1cd4deecc1ef34c8
13 http request GET https://registry.npmjs.org/uikit-site/latest
14 http 404 https://registry.npmjs.org/uikit-site/latest
```
**https://registry.npmjs.org/uikit-site** is not found;
right url is 
> https://www.npmjs.com/package/uikit

**Comment by florianletsch** [comment] 2017-05-12 13:59
I could not reproduce this (on macOS)... So am I right in assuming this is an issue on Windows only?

Can anyone confirm? Any ideas what would be a fix?

**Comment by Intiligent** [comment] 2017-05-12 14:25
@florianletsch describe your issue. I also did not start the first time. In my situation was wrong repository url.

**Comment by florianletsch** [comment] 2017-05-12 14:32
I don't have this issue myself. Just trying to find out if this needs solving. Otherwise I'd close this issue. ;)

**Closed** 2017-06-09 11:04 UTC
